name: Push Docker Images to GHCR

env:
  DOTNET_VERSION: '8.0.x'

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
      push-images:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                solutions:
                    - { key: "console" , value: "DreamTeamOptimizer.ConsoleApp" }
                    - { key: "ms-employee" , value: "DreamTeamOptimizer.MsEmployee" }
                    - { key: "ms-hr-manager" , value: "DreamTeamOptimizer.MsHrManager" }
                    - { key: "ms-hr-director" , value: "DreamTeamOptimizer.MsHrDirector" }
        defaults:
          run:
            working-directory: './Store'
        steps:
          - name: Checkout repository
            uses: actions/checkout@main
          - name: Login to GitHub Container Registry
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.ACCESS_TOKEN }}
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
            with:
              images: ghcr.io/${{ github.repository }}-${{ matrix.solutions.key }}
          - name: Build and Push Docker image
            uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
            with:
              context: .
              file: ./src/${{ matrix.solutions.value }}/Dockerfile
              push: true
              tags: |
                ghcr.io/${{ github.repository }}-${{ matrix.solutions.key }}:latest
                ghcr.io/${{ github.repository }}-${{ matrix.solutions.key }}:${{ github.ref_name }}
              labels: ${{ steps.meta.outputs.labels }}
